@extends('admin.layouts.app')
@section('content')
<h1 class="text-2xl font-black">تنظیمات سایت</h1>
<form method="POST" action="{{ route('admin.settings.update') }}" class="bg-white p-6 rounded-xl mt-5 max-w-4xl space-y-4">@csrf @method('PUT')
<h2 class="font-black text-lg">اطلاعات سایت</h2><input name="site_name" value="{{ old('site_name',\App\Models\Setting::get('site_name','سازمت')) }}" class="w-full rounded-lg border" placeholder="نام سایت"><textarea name="site_description" class="w-full rounded-lg border" placeholder="توضیحات">{{ old('site_description',\App\Models\Setting::get('site_description','بازار آنلاین صنعت ساختمان')) }}</textarea><input name="contact_email" value="{{ old('contact_email',\App\Models\Setting::get('contact_email','info@sazmat.com')) }}" class="w-full rounded-lg border" placeholder="ایمیل تماس">
<div class="border-t pt-5"><h2 class="font-black text-lg">اطلاعات ورود مدیر</h2><p class="text-sm text-gray-500 mt-1">ایمیل فعلی و رمز مدیر را از همین بخش می‌توانید عوض کنید. رمز قبلی نمایش داده نمی‌شود.</p><input name="admin_email" type="email" value="{{ old('admin_email',auth()->user()->email) }}" class="w-full rounded-lg border mt-4" placeholder="ایمیل مدیر"><input name="admin_password" type="password" class="w-full rounded-lg border mt-3" placeholder="رمز جدید مدیر (اختیاری)"><input name="admin_password_confirmation" type="password" class="w-full rounded-lg border mt-3" placeholder="تکرار رمز جدید"></div>
<div class="border-t pt-5"><h2 class="font-black text-lg">پلن‌های اشتراک</h2><p class="text-sm text-gray-500 mt-1">ساخت/ویرایش/غیرفعال‌کردن پلن‌های خدمات و محصولات به بخش جداگانه‌ی «پلن‌های اشتراک» در منوی کناری منتقل شد.</p><a href="{{ route('admin.plans.index') }}" class="btn-primary inline-block mt-3">رفتن به پلن‌های اشتراک</a></div>
<button class="btn-primary">ذخیره همه تنظیمات</button></form>
@endsection
