@extends('layouts.app')
@section('title','سبد خرید')
@section('content')
<div class="container" style="padding-top:32px;padding-bottom:60px;">
    <div style="display:flex;justify-content:space-between;align-items:flex-end;gap:16px;flex-wrap:wrap;"><div><h1>سبد خرید</h1><p style="color:var(--color-steel);margin-top:6px;">محصولاتی که برای خرید انتخاب کرده‌ای اینجا هستند.</p></div><a href="{{ route('products') }}" class="btn btn-ghost">ادامه خرید</a></div>
        @if(!$items)
                <div class="corner-card" style="padding:42px 24px;text-align:center;margin-top:28px;"><div style="font-size:2rem;">🛒</div><h2 style="margin-top:12px;font-size:1.2rem;">سبد خرید خالی است</h2><p style="color:var(--color-steel);margin:8px 0 20px;">هنوز محصولی برای خرید انتخاب نکرده‌ای.</p><a class="btn btn-navy" href="{{ route('products') }}">مشاهده محصولات</a></div>
                    @else
                            <div class="cart-layout" style="margin-top:28px;">
                                        <div class="cart-items">
                                                    @foreach($items as $item)
                                                                    <div class="corner-card cart-item" style="padding:18px;">
                                                                                        <a href="{{ route('ad.show',$item['ad']->slug) }}" class="cart-item-media">@if($item['ad']->primaryImage)<img src="{{ Storage::url($item['ad']->primaryImage->path) }}" alt="{{ $item['ad']->title }}" loading="lazy">@else<span data-icon="box"></span>@endif</a>
                                                                                                            <div class="cart-item-info"><a class="cart-item-title" href="{{ route('ad.show',$item['ad']->slug) }}">{{ $item['ad']->title }}</a><div class="cart-item-price">{{ $item['ad']->price_formatted }} تومان</div><div style="font-size:.82rem;color:var(--color-steel-light);margin-top:4px;">مبلغ این مورد: {{ number_format($item['subtotal']) }} تومان</div></div>
                                                                                                                                <form method="POST" action="{{ route('cart.update',$item['ad']) }}" class="cart-qty-form">@csrf @method('PATCH')<span class="cart-qty-label">تعداد</span><div class="qty-control"><button type="button" class="qty-btn" data-qty-minus>−</button><input type="number" name="quantity" min="1" max="99" value="{{ $item['quantity'] }}" aria-label="تعداد"><button type="button" class="qty-btn" data-qty-plus>+</button></div><button class="qty-update-btn" type="submit">به‌روزرسانی موارد</button></form>
                                                                                                                                                    <form method="POST" action="{{ route('cart.remove',$item['ad']) }}" class="cart-remove">@csrf @method('DELETE')<button type="submit" class="text-red-600">حذف</button></form>
                                                                                                                                                                    </div>
                                                                                                                                                                                @endforeach
                                                                                                                                                                                            </div>
                                                                                                                                                                                                        <aside class="corner-card cart-summary" style="padding:24px;"><h2 style="font-size:1.1rem;">خلاصه سبد</h2><div class="summary-row"><span>تعداد اقلام</span><strong>{{ array_sum(array_column($items,'quantity')) }}</strong></div><div class="summary-total"><span>جمع</span><strong>{{ number_format($total) }} تومان</strong></div><a id="goToCheckout" class="btn btn-primary btn-block" href="{{ route('checkout') }}">ادامه و پرداخت</a><p style="font-size:.78rem;color:var(--color-steel-light);line-height:1.7;margin-top:10px;">هزینه و اطلاعات تحویل در مرحله بعد ثبت می‌شود.</p></aside>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                    @endif
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                    @endsection
                                                                                                                                                                                                                    @push('scripts')
                                                                                                                                                                                                                    <script>
                                                                                                                                                                                                                    document.querySelectorAll('[data-qty-minus],[data-qty-plus]').forEach(btn=>btn.addEventListener('click',()=>{const input=btn.closest('.qty-control').querySelector('input');let v=parseInt(input.value||1,10);v=btn.hasAttribute('data-qty-minus')?Math.max(1,v-1):Math.min(99,v+1);input.value=v;}));

                                                                                                                                                                                                                    document.getElementById('goToCheckout')?.addEventListener('click', function (e) {
                                                                                                                                                                                                                        e.preventDefault();
                                                                                                                                                                                                                            const link = this;
                                                                                                                                                                                                                                const originalText = link.textContent;
                                                                                                                                                                                                                                    link.textContent = 'در حال به‌روزرسانی...';
                                                                                                                                                                                                                                        link.style.pointerEvents = 'none';

                                                                                                                                                                                                                                            const forms = [...document.querySelectorAll('.cart-qty-form')];

                                                                                                                                                                                                                                                Promise.all(forms.map(form => fetch(form.action, {
                                                                                                                                                                                                                                                        method: 'POST',
                                                                                                                                                                                                                                                                body: new FormData(form),
                                                                                                                                                                                                                                                                        headers: { 'X-Requested-With': 'XMLHttpRequest' },
                                                                                                                                                                                                                                                                            }).catch(() => null)))
                                                                                                                                                                                                                                                                                .then(() => { window.location.href = link.href; })
                                                                                                                                                                                                                                                                                    .catch(() => { window.location.href = link.href; });
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                    </script>
                                                                                                                                                                                                                                                                                    @endpush